config/routes.rb
Rails.application.routes.draw do
  root 'artists#index'

  resources :lps
  resources :artists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :lps, dependent: :destroy

  validates :name, uniqueness: true
  validates :description, :name, presence: true
end

app/models/lp.rb
class Lp < ApplicationRecord
  belongs_to :artist

  validates :description, :name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      flash[:success] = ["Artist created succesfully"]
      redirect_to artist_path(@artist)
    else
      flash.now[:danger] = @artist.errors.full_messages
      render :new
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @lps = @artist.lps.order(:name)
  end

  def index
    @artists = Artist.all.order(:name)
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      flash[:success] = ["Artist updated succesfully"]
      redirect_to artist_path(@artist)
    else
      flash.now[:danger] = @artist.errors.full_messages
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id]).destroy
    flash[:success] = ["Artist deleted succesfully"]
    redirect_to root_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :description)
  end

end

app/controllers/lps_controller.rb
class LpsController < ApplicationController

  def new
    @lp = Lp.new
  end

  def create
    @lp = Lp.new(lp_params)
    if @lp.save
      flash[:success] = ["LP created succesfully"]
      redirect_to artist_path(params[:lp][:artist_id])
    else
      params[:artist] = @lp.artist.id if params[:artist]
      flash.now[:danger] = @lp.errors.full_messages
      render :new
    end
  end

  def show
    @lp = Lp.find(params[:id])
  end

  def index
    if params[:keyword]
      @lps = Lp.joins(:artist).where("artists.name LIKE ?", "%" + params[:keyword] + "%").order(:name)
    else
      @lps = Lp.includes(:artist).all.order(:name)
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def edit
    @lp = Lp.find(params[:id])
  end

  def update
    @lp = Lp.find(params[:id])
    if @lp.update(lp_params)
      flash[:success] = ["LP updated succesfully"]
      redirect_to artist_path(params[:lp][:artist_id])
    else
      params[:artist] = @lp.artist.id if params[:artist]
      flash.now[:danger] = @lp.errors.full_messages
      render :edit
    end
  end

  def destroy
    @lp = Lp.find(params[:id]).destroy
    flash[:success] = ["LP deleted succesfully"]
    redirect_to artist_path(@lp.artist)
  end

  private

  def lp_params
    params.require(:lp).permit(:name, :description, :artist_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def add_form_header
    if action_name == "edit"
      return "Edit #{@artist.name}"
    end
    "Add an Artist"
  end
end

app/helpers/lps_helper.rb
module LpsHelper
  def add_lp_form_header
    if action_name == "edit"
      return "Edit #{@lp.name}"
    end
    "Add an LP"
  end
end

app/views/artists/_form.html.erb
<div class="row form-row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <h3 class="w-100 text-center"><%= add_form_header %></h3>
      </div>
      <div class="card-body">
        <%= form_for @artist do |f| %>
          <div class="form-group">
            <label for="artist_name">Name</label>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="artist_description">Description</label>
            <%= f.text_area :description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Save", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/artists/edit.html.erb
<%= render "form" %>

app/views/artists/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <% @artists.each do |ar| %>
      <div class="card artist-card mt-3">
        <div class="card-header">
          <h4><%= link_to ar.name, artist_path(ar) %></h4>
        </div>
        <p class="card-body">
          <%= ar.description %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/artists/new.html.erb
<%= render "form" %>

app/views/artists/show.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header artist-header">
        <h3 class="card-title"><%= @artist.name %></h3> <span><%= pluralize(@artist.lps.count, "LP") %></span><br>
        <small>
          <%= link_to "Edit", edit_artist_path(@artist) %> |
          <%= link_to 'Delete', artist_path(@artist), data: { confirm: 'Are you sure?' }, method: :delete %>
        </small><br>
      </div>
      <div class="card-body">
        <p class="card-text"><%= @artist.description %></p>
      </div>
    </div>

    <div class="card mt-3">
      <div class="card-header">
        <h3 class="card-title">LPs</h3> <%= link_to "+Add LP", new_lp_path(artist: @artist) %>
      </div>
      <div class="card-body lps-body">
        <ul>
          <% @lps.each do |lp| %>
            <li>
              <strong><%= lp.name %></strong>
              <small>
                <%= link_to "Edit", edit_lp_path(lp, artist: @artist), class: "edit-lp-link" %> |
                <%= link_to 'Delete', lp_path(lp), data: { confirm: 'Are you sure?' }, class: "delete-lp-link", method: :delete %>
              </small>
            </li>
            <p class="card-text"><%= lp.description %></p>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Discography</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <span class="navbar-brand">Discography</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-">
            <%= link_to "Artists", artists_path, class: "nav-link" %> <span class="sr-only">(current)</span>
          </li>
          <li class="nav-">
            <%= link_to "LPs", lps_path, class: "nav-link" %> <span class="sr-only">(current)</span>
          </li>
          <li class="nav-item">
            <%= link_to "New Artist", new_artist_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "New LP", new_lp_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </nav>
    <div class="row alert-row">
      <div class="col-sm-12">
        <% flash.each do |key, value| %>
          <% value.each do |v| %>
            <div class="alert alert-<%= key %>"><%= v %></div>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/lps/_form.html.erb
<div class="row form-row">
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header">
        <h3 class="w-100 text-center"><%= add_lp_form_header %></h3>
      </div>
      <div class="card-body">
        <%= form_for @lp do |f| %>
          <div class="form-group">
            <label for="lp_name">Name</label>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <label for="lp_artist_id">Artist</label>
            <%= f.collection_select(:artist_id, Artist.all, :id, :name, {include_blank: "Select an artist...", selected: params[:artist]}, class: "form-control") %>
          </div>
          <div class="form-group">
            <label for="lp_description">Description</label>
            <%= f.text_area :description, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.submit "Save", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lps/_lps.html.erb
<ul class="lp-list">
  <% @lps.each do |lp| %>
    <li><%= link_to lp.name, artist_path(lp.artist&.id) %> <small>(<%= lp.artist&.name %>)</small></li>
  <% end %>
</ul>

app/views/lps/edit.html.erb
<%= render "form" %>

app/views/lps/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <div class="card">
      <div class="card-header">
        <span>Search</span>
      </div>
      <div class="card-body">
        <%= form_tag lps_path, method: "get", remote: true do %>
          <div class="form-group">
            <%= text_field_tag 'keyword', params[:keyword], placeholder: "Filter by artist name", class: "form-input" %>
            <%= submit_tag "Search", class: "form-input" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-12">
    <div class="card mt-3">
      <div class="card-body lp-list-cont">
        <%= render "lps" %>
      </div>
    </div>
  </div>
</div>

app/views/lps/index.js.erb
$('.lp-list-cont').html("<%= j render(partial: 'lps') %>");

app/views/lps/new.html.erb
<%= render "form" %>

app/views/lps/show.html.erb
<%= @lp.name %>